version: '3.6'

services:
  so1:
    image: ${SPLUNK_IMAGE:-splunk/splunk:8.2}
    container_name: so1
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=changeme
    ports:
      - 8000:8000
      - 8088:8088